# Permalinks
permalink:           pretty

# Setup
title:               Dyllan J.R. Usher
tagline:             Data Driven Dyllan
url:                 http://Dyllanjrusher.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Dyllan Usher
  url:               https://www.linkedin.com/in/dyllan-usher-1b35741a8/
  email:             Dyllanjrusher00@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/Dyllanjrusher

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
